/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.9/samples
 */

tasks.register("buildAll") {
    dependsOn(gradle.includedBuilds.map { it.task(":${it.name}:build") })
}

tasks.register("publishAllToMavenLocal") {
    dependsOn(gradle.includedBuilds.map { it.task(":${it.name}:publishToMavenLocal") })
}